config/routes.rb
Rails.application.routes.draw do
  
  root 'demo#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  
  resources :sections do
    member do
      get :delete
    end
  end
  
  resources :pages do
    member do
      get :delete
    end
  end
  
  resources :subjects do
    member do
      get :delete
    end
  end
  
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  #get "demo/index"  #Simple (matching) route
  #match "demo/index", :to => "demo#index", :via => :get # Longer version of a simple route
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  
  has_secure_password
  has_and_belongs_to_many :pages, :join_table => 'admin_users_pages'
  has_many :section_edits
  has_many :sections, :through => :section_edits
  
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_NAMES = ['Jordan', 'test', 'mary']
  
  validates :first_name, presence: true, length: { maximum: 25}
  validates :last_name, presence: true, length: { maximum: 50 }
  #validates :username, presence: true, length: { within: 8..25 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 100 }, format: { with: EMAIL_REGEX }, confirmation: true
  
  validate :first_name_is_allowed
  
  private
  
  def first_name_is_allowed
    if FORBIDDEN_NAMES.include?(first_name)
      errors.add(:first_name, "has been restricted from use.")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  has_and_belongs_to_many :admin_users, :join_table => 'admin_users_pages'
  belongs_to :subject, { :optional => false}
  has_many :sections
  
  scope :sorted, lambda { order("position ASC ") }
  scope :page_sections, lambda { Section.order("position") }
  scope :page_count, lambda { Page.count }
  
  validates :name, presence: true, length: { within: 4..55 }
  validates :permalink, presence: true, length: { within: 3..255 }, uniqueness: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page, { :optional => false}
  has_many :section_edits
  has_many :admin_users, :through => :section_edits
  
  scope :red, -> { where(color: 'red') }
  scope :page_section, -> {  Page.all } # This scope didn't work out
  
  CONTENT_TYPES = ['Text', 'HTML']
  
  validates :name, presence: true, length: { within: 4..55 }
  validates :position, numericality: { only_integer: true}
  validates :content_type, inclusion: { in: CONTENT_TYPES ,
    message: "Must be one of: #{CONTENT_TYPES.join(', ')} "}
  validates :content, presence: true
  
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  belongs_to :section
  belongs_to :admin_user
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
  
#  validates_presence_of :name
  validates :name, presence: true, length: { within: 4..55 }
  validates :position, numericality: { only_integer: true }, allow_nil: false
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  layout 'admin'
  def menu
  end

  def login
  end
  
  def attempt_login
  end
  
  def logout
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  def index
    render('index')
  end
  
  def hello
    render('hello')
  end
  
  def other_hello
    redirect_to(:controller => 'demo', :action => 'index')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  layout 'admin'
  before_action :find_subjects, :only => [:new, :create, :edit, :update]
  before_action :set_page_count, :only => [:new, :create, :edit, :update]
  
  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def edit
    @page = Page.find(params[:id])
    @page_sections = Page.page_sections
  end
  
  def update
    @page = Page.find(params[:id])
    
    if @page.update_attributes(page_params)
      flash[:notice] = "Page updated successfully"
      redirect_to(page_path(@page))
    else
      @page_sections = Page.page_sections
      render 'edit'
    end
  end

  def new
    @page = Page.new
    @page_sections = Page.page_sections
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to(pages_path) #It redirects to index
    else
      @page_sections = Page.page_sections
      render('new')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end
  
  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Flash destroyed successfully"
    redirect_to(pages_path)
  end
  
  private
  def page_params
    params.require(:page).permit(:name, :permalink, :position, :visible, :subject_id)
  end
  
  def find_subjects
    @pages = Page.sorted
  end
  
  def set_page_count
    @page_count = Page.count
    if params[:action] == 'new' || params[:action] == 'create'
      @page_count += 1
    end
  end
  
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  layout 'admin'
  
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
    @section_count = Section.count + 1
  end
  
  def create
    @section = Section.new(section_params)
    
    if @section.save
      flash[:notice] = "Page created successfully."
      redirect_to(sections_path)
    else
      @section_count = Section.count
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
  end
  
  def update
    @section = Section.find(params[:id])
    
    if @section.update_attributes(section_params)
      flash[:notice] = "Subject created successfully."
      redirect_to(section_path(@section))
    else
      @section_count = Section.count
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end
  
  def destroy
    @section = Section.find(params[:id])
    if @section.destroy
      flash[:notice] = "Subject created successfully."
      redirect_to(sections_path)
    end
  end
  
  private
  def section_params
    params.require(:section).permit(:name, :position, :visible, :content, :content_type, :page_id)
    
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout 'admin'
  
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new(:name => "hi")
    @subject_count = Subject.count + 1
  end
  
  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = "Subject created successfully."
      redirect_to(subjects_path) #It redirects to index
    else
      @subject_count = Subject.count
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end
  
  def update
    @subject = Subject.find(params[:id])
    
    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated successfully."
      redirect_to(subject_path(@subject)) #It redirects to show
    else
      @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end
  
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' deleted successfully."
    redirect_to(subjects_path) #It redirects to index
  end
  
  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end
    
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end
  
  def status_tag(boolean, options={})
    options[:true_text] ||= ''
    options[:false_text] ||= ''
    
    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end
  
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
 
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/access/login.html.erb
<% page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log in") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as:</div>
  <ul>
    <li><%= link_to("Manage Subjects", subjects_path) %></li>
    <li><%= link_to("Manage Pages", pages_path) %></li>
    <li><%= link_to("Manage Sections", sections_path) %></li>
    <li><%= link_to("Manage Admin Users", '#') %></li>
    <li><%= link_to("Logout", access_logout_path) %></li>
  </ul>
</div>

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %>  prohibited this record from being saved </h2>
    <p>There were problems with the following fields: </p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/demo/hello.html.erb
<h1>Hello from hello views</h1>

<a href="/demo/hello">Hello page 1</a><br/>
 

app/views/demo/index.html.erb
<h1>Hello from index</h1>
<hr/>

<%= link_to("Subjects", subjects_path) %><br/>
<%= link_to("Pages", pages_path) %><br/>
<%= link_to("Sections", sections_path) %><br/>

app/views/layouts/admin.html.erb
<html>
  <head>
    <title>Simple CMS: <%= @page_title || "Admin Area" %> </title>
    <%= stylesheet_link_tag('admin', :media => 'all') %>
  </head>
  
  <body>
    
    <div id="header">
      <h1>Simple CMS Admin</h1>
    </div>
    
    <div id="main">
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      
      <div id="content">
        <%= yield %>
      </div>
    </div>
    
    <div id="footer">
      <p id="copyright">&copy; AC Alexandre Calaça</p>
    </div>
  </body> 
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Subject</th>
    <td><%= f.select(:subject_id, @page_sections.collect {|p| [p.name, p.id] }, include_blank: true) %></td>
  </tr>
</table>

app/views/pages/create.html.erb
<h1>Pages#create</h1>
<p>Find me in app/views/pages/create.html.erb</p>

app/views/pages/delete.html.erb
<%= link_to("<< Back to list", pages_path,  :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>
  
  <%= form_for(@page, :url => page_path(@page), :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this page? </p>
    <p class="reference-name"><%= f.object.name %></p>
    
    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>
    
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>

<div class="pages edit">
  <h2>Update page</h2>
  
  <%= form_for(@page, :url => page_path(@page), :method => 'patch') do |f| %>
    
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>
    
  <% end %>
</div>  

app/views/pages/index.html.erb
<div class="pages index">
  <h2>Pages</h2>
  
  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>
  
    <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Visible</th>
      <th>Subject</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.name %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"><%= page.subject.name %></td>
      <td class="actions">
        <%= link_to("Show", page_path(page.id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>  
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create page</h2>
  
  <%= form_for(@page, :url => pages_path, :method => 'post') do |f| %>
    
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>
  <% end %>
</div>  

app/views/pages/show.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>
  
  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Subject id</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Section form fields">
  
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@section_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Content type</th>
    <td>
      <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML
    </td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :size => '40x10') %></td>
  </tr>
  <tr>
    <th>Page</th>
     <td><%= f.select :page_id, Section.page_section.collect { |p| [p.name,p.id] }, include_blank: true %></td>

  </tr>
</table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to list", sections_path,  :class => 'back-link') %>

<div class="sections delete">
  <h2>Delete Section</h2>
  
  <%= form_for(@section, :url => section_path(@section), :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this section? </p>
    <p class="reference-name"><%= f.object.name %></p>
    
    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>
    
  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>

<div class="sections edit">
  <h2>Update section</h2>
  
  <%= form_for(@section, :url => section_path(@section), :method => 'patch') do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    
    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>
    
  <% end %>
</div>  

app/views/sections/index.html.erb
<div class="sections index">
  <h2>Sections</h2>
  
  <%= link_to("Add New Section", new_section_path, :class => 'action new') %>
  
  <table class="listing" summary="Section list">
    <tr class="header">
      <th>#</th>
      <th>Section name</th>
      <th>Visible</th>
      <th>Content type</th>
      <th>Content</th>
      <th>Page id</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.name %></td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="center"><%= section.content_type %></td>
      <td class="center"><%= section.content %></td>
      <td class="center"><%= section.page_id %></td>
      <td class="actions">
        <%= link_to("Show", section_path(section.id), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>

<div class="sections new">
  <h2>Create section</h2>
  
  <%= form_for(@section, :url => sections_path, :method => 'post') do |f| %>
  
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    
    
    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>
    
    
  <% end %>
</div>  

app/views/sections/show.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>

<div class="sections show">
  <h2>Show Section</h2>
  
  <table summary="Section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Page id</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>
</div>

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Created</th>
    <td><%= f.datetime_select(:created_at) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to list", subjects_path,  :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>
  
  <%= form_for(@subject, :url => subject_path(@subject), :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this subject? </p>
    <p class="reference-name"><%= f.object.name %></p>
    
    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>
    
  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update subject</h2>
  
  <%= form_for(@subject, :url => subject_path(@subject), :method => 'patch') do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>
    
    
  <% end %>
</div>  

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>
  
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>
  
  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject.id), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject.id), :class => 'action show') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create subject</h2>
  
  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>
    
    
  <% end %>
</div>  

app/views/subjects/show.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>
  
  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>